const charms = [
  { id: 1, nome: "Bússola Caprichosa", categoria: "Charms" },
  { id: 2, nome: "Enxame de Colecionadores", categoria: "Charms" },
  { id: 3, nome: "Carapaça Robusta", categoria: "Charms" },
  { id: 4, nome: "Apanhador de Almas", categoria: "Charms" },
  { id: 5, nome: "Pedra do Xamã", categoria: "Charms" },
  { id: 6, nome: "Devorador de Almas", categoria: "Charms" },
  { id: 7, nome: "Mestre da Esquiva", categoria: "Charms" },
  { id: 8, nome: "Mestre da Corrida", categoria: "Charms" },
  { id: 9, nome: "Canção das Larvas", categoria: "Charms" },
  { id: 10, nome: "Elegia da Larvamosca", categoria: "Charms" },
  { id: 11, nome: "Coração Frágil", categoria: "Charms" },
  { id: 12, nome: "Ganância Frágil", categoria: "Charms" },
  { id: 13, nome: "Força Frágil", categoria: "Charms" },
  { id: 14, nome: "Dobrador de Magias", categoria: "Charms" },
  { id: 15, nome: "Corpo Firme", categoria: "Charms" },
  { id: 16, nome: "Golpe Pesado", categoria: "Charms" },
  { id: 17, nome: "Corte Rápido", categoria: "Charms" },
  { id: 18, nome: "Ferrão Longo", categoria: "Charms" },
  { id: 19, nome: "Marca de Orgulho", categoria: "Charms" },
  { id: 20, nome: "Fúria dos Caídos", categoria: "Charms" },
  { id: 21, nome: "Espinhos da Agonia", categoria: "Charms" },
  { id: 22, nome: "Carapaça de Baldur", categoria: "Charms" },
  { id: 23, nome: "Ninho de Flukes", categoria: "Charms" },
  { id: 24, nome: "Insígnia do Defensor", categoria: "Charms" },
  { id: 25, nome: "Útero Brilhante", categoria: "Charms" },
  { id: 26, nome: "Foco Rápido", categoria: "Charms" },
  { id: 27, nome: "Foco Profundo", categoria: "Charms" },
  { id: 28, nome: "Coração de Sangue Vital", categoria: "Charms" },
  { id: 29, nome: "Núcleo de Sangue Vital", categoria: "Charms" },
  { id: 30, nome: "Bênção de Joni", categoria: "Charms" },
  { id: 31, nome: "Sangue da Colmeia", categoria: "Charms" },
  { id: 32, nome: "Cogumelo com Esporos", categoria: "Charms" },
  { id: 33, nome: "Sombra Afiada", categoria: "Charms" },
  { id: 34, nome: "Forma de Unn", categoria: "Charms" },
  { id: 35, nome: "Glória do Mestre do Ferrão", categoria: "Charms" },
  { id: 36, nome: "Canção das Tecelãs", categoria: "Charms" },
  { id: 37, nome: "Portador dos Sonhos", categoria: "Charms" },
  { id: 38, nome: "Escudo dos Sonhos", categoria: "Charms" },
  { id: 39, nome: "Criança Grimm", categoria: "Charms" },
  { id: 40, nome: "Alma do Rei", categoria: "Charms" }
];