const itens = [
  { id: 1, nome: "Bússola Caprichosa", categoria: "Amuletos", imagem: "imgs/charm-1.png" },
  { id: 2, nome: "Enxame de Colecionadores", categoria: "Amuletos", imagem: "imgs/charm-2.png" },
  { id: 3, nome: "Carapaça Robusta", categoria: "Amuletos", imagem: "imgs/charm-3.png" },
  { id: 4, nome: "Apanhador de Almas", categoria: "Amuletos", imagem: "imgs/charm-4.png" },
  { id: 5, nome: "Pedra do Xamã", categoria: "Amuletos", imagem: "imgs/charm-5.png" },
  { id: 6, nome: "Devorador de Almas", categoria: "Amuletos", imagem: "igs/charm-6.png" },
  { id: 7, nome: "Mestre da Esquiva", categoria: "Amuletos", imagem: "imgs/charm-7.png" },
  { id: 8, nome: "Mestre da Corrida", categoria: "Amuletos", imagem: "imgs/charm-8.png" },
  { id: 9, nome: "Canção das Larvas", categoria: "Amuletos", imagem: "imgs/charm-9.png" },
  { id: 10, nome: "Elegia da Larvamosca", categoria: "Amuletos", imagem: "imgs/charm-10.png" },
  { id: 11, nome: "Coração Frágil", categoria: "Amuletos", imagem: "imgs/charm-11.png" },
  { id: 12, nome: "Ganância Frágil", categoria: "Amuletos", imagem: "imgs/charm-12.png" },
  { id: 13, nome: "Força Frágil", categoria: "Amuletos", imagem: "imgs/charm-13.png" },
  { id: 14, nome: "Dobrador de Magias", categoria: "Amuletos", imagem: "imgs/charm-14.png" },
  { id: 15, nome: "Corpo Firme", categoria: "Amuletos", imagem: "imgs/charm-15.png" },
  { id: 16, nome: "Golpe Pesado", categoria: "Amuletos", imagem: "imgs/charm-16.png" },
  { id: 17, nome: "Corte Rápido", categoria: "Amuletos", imagem: "imgs/charm-17.png" },
  { id: 18, nome: "Ferrão Longo", categoria: "Amuletos", imagem: "imgs/charm-18.png" },
  { id: 19, nome: "Marca de Orgulho", categoria: "Amuletos", imagem: "imgs/charm-19.png" },
  { id: 20, nome: "Fúria dos Caídos", categoria: "Amuletos", imagem: "imgs/charm-20.png" },
  { id: 21, nome: "Espinhos da Agonia", categoria: "Amuletos", imagem: "imgs/charm-21.png" },
  { id: 22, nome: "Carapaça de Baldur", categoria: "Amuletos", imagem: "imgs/charm-22.png" },
  { id: 23, nome: "Ninho de Flukes", categoria: "Amuletos", imagem: "imgs/charm-23.png" },
  { id: 24, nome: "Insígnia do Defensor", categoria: "Amuletos", imagem: "imgs/charm-24.png" },
  { id: 25, nome: "Útero Brilhante", categoria: "Amuletos", imagem: "imgs/charm-25.png" },
  { id: 26, nome: "Foco Rápido", categoria: "Amuletos", imagem: "imgs/charm-26.png" },
  { id: 27, nome: "Foco Profundo", categoria: "Amuletos", imagem: "imgs/charm-27.png" },
  { id: 28, nome: "Coração de Sangue Vital", categoria: "Amuletos", imagem: "imgs/charm-28.png" },
  { id: 29, nome: "Núcleo de Sangue Vital", categoria: "Amuletos", imagem: "imgs/charm-29.png" },
  { id: 30, nome: "Bênção de Joni", categoria: "Amuletos", imagem: "imgs/charm-30.png" },
  { id: 31, nome: "Sangue da Colmeia", categoria: "Amuletos", imagem: "imgs/charm-31.png" },
  { id: 32, nome: "Cogumelo com Esporos", categoria: "Amuletos", imagem: "imgs/charm-32.png" },
  { id: 33, nome: "Sombra Afiada", categoria: "Amuletos", imagem: "imgs/charm-33.png" },
  { id: 34, nome: "Forma de Unn", categoria: "Amuletos", imagem: "imgs/charm-34.png" },
  { id: 35, nome: "Glória do Mestre do Ferrão", categoria: "Amuletos", imagem: "imgs/charm-35.png" },
  { id: 36, nome: "Canção das Tecelãs", categoria: "Amuletos", imagem: "imgs/charm-36.png" },
  { id: 37, nome: "Portador dos Sonhos", categoria: "Amuletos", imagem: "imgs/charm-37.png" },
  { id: 38, nome: "Escudo dos Sonhos", categoria: "Amuletos", imagem: "imgs/charm-38.png" },
  { id: 39, nome: "Criança Grimm", categoria: "Amuletos", imagem: "imgs/charm-39.png" },
  { id: 40, nome: "Alma do Rei", categoria: "Amuletos", imagem: "imgs/charm-40.png" },
  // ---------- Ferrões ----------
  { id: 41, nome: "Ferrão Afiado", categoria: "Ferrao", imagem: "imgs/nail-41.webp" },
  { id: 42, nome: "Ferrão Canalizado", categoria: "Ferrao", imagem: "imgs/nail-42.webp" },
  { id: 43, nome: "Ferrão Serpenteado", categoria: "Ferrao", imagem: "imgs/nail-43.webp" },
  { id: 44, nome: "Ferrão Puro", categoria: "Ferrao", imagem: "imgs/nail-44.webp" },
  // ---------- Chefes ----------
  { id: 45, nome: "Falso Cavaleiro", categoria: "Chefes", imagem: "imgs/boss-45.webp" },
  { id: 46, nome: "Mãe Mosca", categoria: "Chefes", imagem: "imgs/boss-46.webp" },
  { id: 47, nome: "Hornet Protetora", categoria: "Chefes", imagem: "imgs/boss-47.webp" },
  { id: 48, nome: "Hornet Sentinela", categoria: "Chefes", imagem: "imgs/boss-48.webp" },
  { id: 49, nome: "Mawlek Incubador", categoria: "Chefes", imagem: "imgs/boss-49.webp" },
  { id: 50, nome: "Mestre das Almas", categoria: "Chefes", imagem: "imgs/boss-50.webp" },
  { id: 51, nome: "Lordes Louva-a-Deus", categoria: "Chefes", imagem: "imgs/boss-51.webp" },
  { id: 52, nome: "Defensor do Esterco", categoria: "Chefes", imagem: "imgs/boss-52.webp" },
  { id: 53, nome: "Cavaleiro da Colmeia", categoria: "Chefes", imagem: "imgs/boss-53.webp" },
  { id: 54, nome: "Nosk", categoria: "Chefes", imagem: "imgs/boss-54.webp" },
  { id: 55, nome: "Receptáculo Quebrado", categoria: "Chefes", imagem: "imgs/boss-55.webp" },
  { id: 56, nome: "Uumuu", categoria: "Chefes", imagem: "imgs/boss-56.webp" },
  { id: 57, nome: "Cavaleiro Sentinela", categoria: "Chefes", imagem: "imgs/boss-57.webp" },
  { id: 58, nome: "O Colecionador", categoria: "Chefes", imagem: "imgs/boss-58.webp" },
  { id: 59, nome: "Lorde Traidor", categoria: "Chefes", imagem: "imgs/boss-59.webp" },
  { id: 60, nome: "Grimm", categoria: "Chefes", imagem: "imgs/boss-60.webp" },
  { id: 61, nome: "Rei do Pesadelo", categoria: "Chefes", imagem: "imgs/boss-61.webp" },

  // ---------- Guerreiros dos Sonhos ----------
  { id: 62, nome: "Xero", categoria: "Chefes dos Sonhos", imagem: "imgs/boss-62.webp" },
  { id: 63, nome: "Gorb", categoria: "Chefes dos Sonhos", imagem: "imgs/boss-63.webp" },
  { id: 64, nome: "Ancião Hu", categoria: "Chefes dos Sonhos", imagem: "imgs/boss-64.webp" },
  { id: 65, nome: "Marmu", categoria: "Chefes dos Sonhos", imagem: "imgs/boss-65.webp" },
  { id: 66, nome: "Sem Olhos", categoria: "Chefes dos Sonhos", imagem: "imgs/boss-66.webp" },
  { id: 67, nome: "Galien", categoria: "Chefes dos Sonhos", imagem: "imgs/boss-67.webp" },
  { id: 68, nome: "Markoth", categoria: "Chefes dos Sonhos", imagem: "imgs/boss-68.webp" }
];